"""Intent agent tests — all Claude calls are mocked."""

from __future__ import annotations

import json
import uuid
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from natural_iac.contract.schema import ComponentRole
from natural_iac.conventions.schema import ConventionProfile, NamingConfig, TagConfig
from natural_iac.intent import IntentAgent
from natural_iac.intent.prompts import build_conventions_section


# ---------------------------------------------------------------------------
# Helpers to build mock Anthropic responses
# ---------------------------------------------------------------------------


def _tool_use_block(name: str, input_data: dict, block_id: str | None = None):
    block = MagicMock()
    block.type = "tool_use"
    block.name = name
    block.id = block_id or f"tu_{uuid.uuid4().hex[:8]}"
    block.input = input_data
    return block


def _text_block(text: str):
    block = MagicMock()
    block.type = "text"
    block.text = text
    return block


def _api_response(*blocks):
    resp = MagicMock()
    resp.content = list(blocks)
    resp.stop_reason = "tool_use" if any(b.type == "tool_use" for b in blocks) else "end_turn"
    return resp


def _minimal_contract_payload(name: str = "test-app") -> dict:
    return {
        "contract": {
            "schema_version": "v1",
            "name": name,
            "description": "A simple test app",
            "components": [
                {
                    "name": "api",
                    "role": "web_api",
                    "requirements": {
                        "availability": "standard",
                        "size_hint": "small",
                        "publicly_accessible": True,
                    },
                },
                {
                    "name": "db",
                    "role": "primary_datastore",
                    "requirements": {
                        "availability": "standard",
                        "size_hint": "small",
                        "publicly_accessible": False,
                    },
                },
            ],
        }
    }


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_client():
    client = MagicMock()
    client.messages = MagicMock()
    client.messages.create = AsyncMock()
    return client


@pytest.fixture
def agent(mock_client):
    return IntentAgent(client=mock_client, model="claude-test", max_clarifications=3)


# ---------------------------------------------------------------------------
# Non-interactive path (no clarification callback)
# ---------------------------------------------------------------------------


class TestNonInteractiveParse:
    @pytest.mark.asyncio
    async def test_emits_contract_on_first_turn(self, agent, mock_client):
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )

        result = await agent.parse("I need a web API with a database")

        assert result.contract.name == "test-app"
        assert len(result.contract.components) == 2
        mock_client.messages.create.assert_called_once()

    @pytest.mark.asyncio
    async def test_id_is_fresh_uuid_not_model_generated(self, agent, mock_client):
        payload = _minimal_contract_payload()
        payload["contract"]["id"] = "model-generated-id-should-be-replaced"
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", payload)
        )

        result = await agent.parse("web api + db")

        # id must be a valid UUID generated by the agent, not the model's value
        assert result.contract.id != "model-generated-id-should-be-replaced"
        uuid.UUID(result.contract.id)  # raises if not valid

    @pytest.mark.asyncio
    async def test_human_reviewed_always_false(self, agent, mock_client):
        payload = _minimal_contract_payload()
        payload["contract"]["human_reviewed"] = True  # model tries to set it
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", payload)
        )

        result = await agent.parse("web api + db")

        assert result.contract.human_reviewed is False

    @pytest.mark.asyncio
    async def test_schema_version_always_v1(self, agent, mock_client):
        payload = _minimal_contract_payload()
        payload["contract"]["schema_version"] = "v99"
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", payload)
        )

        result = await agent.parse("web api + db")

        assert result.contract.schema_version.value == "v1"

    @pytest.mark.asyncio
    async def test_validation_result_attached(self, agent, mock_client):
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )

        result = await agent.parse("web api + db")

        assert result.validation is not None
        # human_reviewed=false produces a warning but no errors
        assert result.validation.passed

    @pytest.mark.asyncio
    async def test_trace_records_intent(self, agent, mock_client):
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )

        result = await agent.parse("I need a web API with a database")

        assert result.trace.intent == "I need a web API with a database"
        assert result.trace.questions_asked == []

    @pytest.mark.asyncio
    async def test_text_block_before_tool_use_is_handled(self, agent, mock_client):
        """Model may emit a text preamble before the tool call — should still work."""
        mock_client.messages.create.return_value = _api_response(
            _text_block("Here is the contract I've built for you:"),
            _tool_use_block("emit_contract", _minimal_contract_payload()),
        )

        result = await agent.parse("web api + db")

        assert result.contract is not None


# ---------------------------------------------------------------------------
# Clarification loop
# ---------------------------------------------------------------------------


class TestClarificationLoop:
    @pytest.mark.asyncio
    async def test_single_clarification_then_emit(self, agent, mock_client):
        clarification_id = "tu_clarify_01"

        # Turn 1: ask a question
        turn1 = _api_response(
            _tool_use_block("ask_clarification", {"question": "Is this customer-facing?"}, clarification_id)
        )
        # Turn 2: emit contract
        turn2 = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )
        mock_client.messages.create.side_effect = [turn1, turn2]

        answers = ["Yes, it's customer-facing in production."]
        answer_iter = iter(answers)

        async def callback(q: str) -> str:
            return next(answer_iter)

        result = await agent.parse("I need a web API", clarification_callback=callback)

        assert result.contract is not None
        assert result.trace.questions_asked == ["Is this customer-facing?"]
        assert mock_client.messages.create.call_count == 2

    @pytest.mark.asyncio
    async def test_no_callback_skips_clarification_questions(self, agent, mock_client):
        """Without a callback, the agent responds to questions with a no-answer sentinel."""
        clarification_id = "tu_clarify_01"
        turn1 = _api_response(
            _tool_use_block("ask_clarification", {"question": "What availability do you need?"}, clarification_id)
        )
        turn2 = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )
        mock_client.messages.create.side_effect = [turn1, turn2]

        result = await agent.parse("I need a web API", clarification_callback=None)

        assert result.contract is not None
        # Question recorded in trace even without callback
        assert "What availability do you need?" in result.trace.questions_asked

    @pytest.mark.asyncio
    async def test_max_clarifications_forces_emit(self, mock_client):
        """After max_clarifications rounds, a forcing message is injected."""
        agent = IntentAgent(client=mock_client, model="claude-test", max_clarifications=2)

        def make_question(i):
            return _api_response(
                _tool_use_block("ask_clarification", {"question": f"Question {i}?"}, f"tu_q{i}")
            )

        emit_response = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )

        # Two questions, then an emit
        mock_client.messages.create.side_effect = [
            make_question(1),
            make_question(2),
            emit_response,
        ]

        answers = iter(["answer 1", "answer 2"])

        async def callback(q: str) -> str:
            return next(answers)

        result = await agent.parse("vague intent", clarification_callback=callback)

        assert result.contract is not None
        assert len(result.trace.questions_asked) == 2
        # The forcing message should appear in the trace
        forcing_turns = [
            t for t in result.trace.turns
            if isinstance(t.content, str) and "forcing emit" in t.content
        ]
        assert len(forcing_turns) == 1


# ---------------------------------------------------------------------------
# Convention injection
# ---------------------------------------------------------------------------


class TestConventionInjection:
    def _profile(self, naming=None, tags=None) -> ConventionProfile:
        return ConventionProfile(
            naming=naming or NamingConfig(),
            tags=tags or TagConfig(),
        )

    def test_naming_variables_appear_in_section(self):
        profile = self._profile(
            naming=NamingConfig(
                pattern="{env}-{component}-{type_short}",
                variables={"env": "dev"},
            )
        )
        section = build_conventions_section(profile)
        assert "env" in section
        assert "dev" in section
        assert "metadata" in section

    def test_required_tags_covered_by_defaults_listed_as_covered(self):
        profile = self._profile(
            tags=TagConfig(
                required=["CostCenter", "ManagedBy"],
                defaults={"CostCenter": "platform-eng", "ManagedBy": "natural-iac"},
            )
        )
        section = build_conventions_section(profile)
        assert "covered by defaults" in section
        assert "CostCenter" in section
        assert "Do NOT ask" in section

    def test_required_tags_without_defaults_flagged_as_missing(self):
        profile = self._profile(
            tags=TagConfig(
                required=["Team"],
                defaults={},
            )
        )
        section = build_conventions_section(profile)
        assert "Team" in section
        assert "NO default" in section
        assert "metadata" in section

    def test_tag_with_variable_placeholder_noted(self):
        profile = self._profile(
            tags=TagConfig(
                required=["Environment"],
                defaults={"Environment": "${env}"},
            )
        )
        section = build_conventions_section(profile)
        assert "Environment" in section
        assert "${env}" in section

    def test_empty_conventions_returns_section_header_only(self):
        profile = self._profile()
        section = build_conventions_section(profile)
        assert "## Org conventions" in section
        # No variable or tag noise
        assert "metadata" not in section
        assert "NO default" not in section

    @pytest.mark.asyncio
    async def test_conventions_injected_into_system_prompt(self, agent, mock_client):
        profile = self._profile(
            naming=NamingConfig(variables={"env": "prod"}),
            tags=TagConfig(required=["Team"], defaults={}),
        )
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )

        await agent.parse("I need a web API", conventions=profile)

        call_kwargs = mock_client.messages.create.call_args
        system_prompt = call_kwargs.kwargs.get("system") or call_kwargs.args[0]
        assert "## Org conventions" in system_prompt
        assert "env" in system_prompt
        assert "Team" in system_prompt

    @pytest.mark.asyncio
    async def test_no_conventions_omits_section(self, agent, mock_client):
        mock_client.messages.create.return_value = _api_response(
            _tool_use_block("emit_contract", _minimal_contract_payload())
        )

        await agent.parse("I need a web API", conventions=None)

        call_kwargs = mock_client.messages.create.call_args
        system_prompt = call_kwargs.kwargs.get("system") or call_kwargs.args[0]
        assert "## Org conventions" not in system_prompt


# ---------------------------------------------------------------------------
# Component role coverage (spot-check that model output maps correctly)
# ---------------------------------------------------------------------------


class TestComponentRoleMapping:
    @pytest.mark.asyncio
    async def test_all_roles_parse(self, agent, mock_client):
        """Ensure every ComponentRole value survives a round-trip through the agent."""
        for role in ComponentRole:
            payload = {
                "contract": {
                    "name": f"test-{role.value.replace('_', '-')}",
                    "components": [{"name": "svc", "role": role.value}],
                }
            }
            mock_client.messages.create.return_value = _api_response(
                _tool_use_block("emit_contract", payload)
            )

            result = await agent.parse(f"I need a {role.value}")

            assert result.contract.components[0].role == role
