"""
HCL renderer - converts an ExecutionPlan into Terraform configuration files.

Design decisions:
- One file per concern: providers.tf, main.tf, outputs.tf
- String property values that start with "${" and end with "}" are rendered
  as Terraform expression references (unquoted), e.g. "${aws_vpc.main.id}"
  renders as: aws_vpc.main.id
- tags on Resource.tags are merged with any "tags" key in Resource.properties;
  Resource.tags wins on conflict.
- Properties with a "tags" key are extracted and handled separately so tags
  are always rendered in a consistent block.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from ...planner.schema import ExecutionPlan, Resource

# Terraform AWS provider version pin
_AWS_PROVIDER_VERSION = "~> 5.0"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_plan(plan: ExecutionPlan) -> dict[str, str]:
    """Render an ExecutionPlan to a dict of {filename -> HCL content}.

    The caller writes these files to whatever working directory it chooses.
    """
    return {
        "providers.tf": _render_providers(plan),
        "main.tf": _render_main(plan),
    }


def render_to_dir(plan: ExecutionPlan, directory: str | Path) -> list[Path]:
    """Write rendered HCL files to *directory*. Returns list of written paths."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, content in render_plan(plan).items():
        path = directory / filename
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


# ---------------------------------------------------------------------------
# File-level renderers
# ---------------------------------------------------------------------------


def _render_providers(plan: ExecutionPlan) -> str:
    lines = [
        'terraform {',
        '  required_providers {',
        '    aws = {',
        '      source  = "hashicorp/aws"',
        f'      version = "{_AWS_PROVIDER_VERSION}"',
        '    }',
        '  }',
        '}',
        '',
        'provider "aws" {',
        f'  region = "{plan.region}"',
        '}',
        '',
    ]
    return "\n".join(lines)


def _render_main(plan: ExecutionPlan) -> str:
    blocks: list[str] = [
        f'# Generated by natural-iac - contract: {plan.contract_name}',
        f'# Plan ID: {plan.id}',
        '',
    ]
    for resource in plan.resources:
        blocks.append(_render_resource(resource))
        blocks.append('')
    return "\n".join(blocks)


# ---------------------------------------------------------------------------
# Resource renderer
# ---------------------------------------------------------------------------


def _render_resource(resource: Resource) -> str:
    lines = [f'resource "{resource.type}" "{resource.logical_name}" {{']

    # Separate tags out of properties so we always render them last and merged.
    props = {k: v for k, v in resource.properties.items() if k != "tags"}
    prop_tags: dict[str, str] = resource.properties.get("tags", {})

    # Render scalar/map/list properties
    for key, value in props.items():
        rendered = _hcl_value(value, indent=1)
        lines.append(f"  {key} = {rendered}")

    # Merged tags: Resource.tags wins over any tags in properties
    merged_tags = {**prop_tags, **resource.tags}
    if merged_tags:
        if props:  # blank line before tags if there were other properties
            lines.append("")
        lines.append("  tags = {")
        for k, v in sorted(merged_tags.items()):
            lines.append(f'    {k} = "{v}"')
        lines.append("  }")

    # depends_on - rendered as resource references, not quoted strings
    if resource.depends_on:
        lines.append("")
        refs = ", ".join(resource.depends_on)
        lines.append(f"  depends_on = [{refs}]")

    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HCL value serialisation
# ---------------------------------------------------------------------------


def _hcl_value(value: Any, indent: int = 0) -> str:
    """Recursively serialise a Python value to its HCL representation.

    Special case: string values wrapped in ``${...}`` are treated as Terraform
    expression references and rendered without quotes.
    """
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        if _is_tf_reference(value):
            return value[2:-1]  # strip ${ and }
        return f'"{_escape_hcl_string(value)}"'
    if isinstance(value, list):
        return _hcl_list(value, indent)
    if isinstance(value, dict):
        return _hcl_map(value, indent)
    # Fallback for anything unexpected
    return f'"{value}"'


def _is_tf_reference(value: str) -> bool:
    """True if the string is a Terraform expression reference: ${...}"""
    return value.startswith("${") and value.endswith("}")


def _escape_hcl_string(value: str) -> str:
    """Escape characters that need escaping inside HCL double-quoted strings."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def _hcl_list(items: list, indent: int) -> str:
    if not items:
        return "[]"
    pad = "  " * (indent + 1)
    close = "  " * indent
    rendered = [_hcl_value(item, indent + 1) for item in items]

    # Single-line if all items are scalars and the line would be short
    if all(_is_scalar(item) for item in items):
        oneliner = "[" + ", ".join(rendered) + "]"
        if len(oneliner) <= 80:
            return oneliner

    inner = "\n".join(f"{pad}{r}," for r in rendered)
    return f"[\n{inner}\n{close}]"


def _hcl_map(mapping: dict, indent: int) -> str:
    if not mapping:
        return "{}"
    pad = "  " * (indent + 1)
    close = "  " * indent
    lines = []
    for k, v in mapping.items():
        lines.append(f"{pad}{k} = {_hcl_value(v, indent + 1)}")
    return "{\n" + "\n".join(lines) + f"\n{close}}}"


def _is_scalar(value: Any) -> bool:
    return isinstance(value, (bool, int, float, str)) or value is None
