"""
HCL renderer - converts an ExecutionPlan into Terraform configuration files.

Design decisions:
- One file per concern: providers.tf, main.tf, outputs.tf
- String property values that start with "${" and end with "}" are rendered
  as Terraform expression references (unquoted), e.g. "${aws_vpc.main.id}"
  renders as: aws_vpc.main.id
- tags on Resource.tags are merged with any "tags" key in Resource.properties;
  Resource.tags wins on conflict.
- Properties with a "tags" key are extracted and handled separately so tags
  are always rendered in a consistent block.
"""

from __future__ import annotations

import warnings
from pathlib import Path
from typing import TYPE_CHECKING, Any

from ...planner.schema import ExecutionPlan, Resource, ResourceKind

if TYPE_CHECKING:
    from ...conventions.schema import ConventionProfile, ModuleOverride

# Terraform AWS provider version pin
_AWS_PROVIDER_VERSION = "~> 5.0"


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def render_plan(
    plan: ExecutionPlan,
    conventions: "ConventionProfile | None" = None,
) -> dict[str, str]:
    """Render an ExecutionPlan to a dict of {filename -> HCL content}.

    The caller writes these files to whatever working directory it chooses.
    """
    return {
        "providers.tf": _render_providers(plan),
        "main.tf": _render_main(plan, conventions),
    }


def render_to_dir(
    plan: ExecutionPlan,
    directory: str | Path,
    conventions: "ConventionProfile | None" = None,
) -> list[Path]:
    """Write rendered HCL files to *directory*. Returns list of written paths."""
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    for filename, content in render_plan(plan, conventions).items():
        path = directory / filename
        path.write_text(content, encoding="utf-8")
        written.append(path)
    return written


# ---------------------------------------------------------------------------
# File-level renderers
# ---------------------------------------------------------------------------


def _render_providers(plan: ExecutionPlan) -> str:
    lines = [
        'terraform {',
        '  required_providers {',
        '    aws = {',
        '      source  = "hashicorp/aws"',
        f'      version = "{_AWS_PROVIDER_VERSION}"',
        '    }',
        '  }',
        '}',
        '',
        'provider "aws" {',
        f'  region = "{plan.region}"',
        '}',
        '',
    ]
    return "\n".join(lines)


def _render_main(
    plan: ExecutionPlan,
    conventions: "ConventionProfile | None" = None,
) -> str:
    blocks: list[str] = [
        f'# Generated by natural-iac - contract: {plan.contract_name}',
        f'# Plan ID: {plan.id}',
        '',
    ]

    data_sources = [r for r in plan.resources if r.kind == ResourceKind.DATA]
    managed = [r for r in plan.resources if r.kind == ResourceKind.RESOURCE]

    # Data sources first so managed resources can reference them
    if data_sources:
        blocks.append('# --- Existing resources (data sources) ---')
        blocks.append('')
        for resource in data_sources:
            blocks.append(_render_data_source(resource))
            blocks.append('')

    if managed:
        blocks.append('# --- Managed resources ---')
        blocks.append('')
        for resource in managed:
            module_override = conventions.module_for(resource.type) if conventions else None
            if module_override is not None:
                blocks.append(_render_module(resource, module_override, conventions))
            else:
                blocks.append(_render_resource(resource))
            blocks.append('')

    return "\n".join(blocks)


# ---------------------------------------------------------------------------
# Resource renderer
# ---------------------------------------------------------------------------


def _render_resource(resource: Resource) -> str:
    lines = [f'resource "{resource.type}" "{resource.logical_name}" {{']

    # Separate tags out of properties so we always render them last and merged.
    props = {k: v for k, v in resource.properties.items() if k != "tags"}
    prop_tags: dict[str, str] = resource.properties.get("tags", {})

    # Render scalar/map/list properties
    for key, value in props.items():
        rendered = _hcl_value(value, indent=1)
        lines.append(f"  {key} = {rendered}")

    # Merged tags: Resource.tags wins over any tags in properties
    merged_tags = {**prop_tags, **resource.tags}
    if merged_tags:
        if props:  # blank line before tags if there were other properties
            lines.append("")
        lines.append("  tags = {")
        for k, v in sorted(merged_tags.items()):
            lines.append(f'    {k} = "{v}"')
        lines.append("  }")

    # depends_on - rendered as resource references, not quoted strings
    if resource.depends_on:
        lines.append("")
        refs = ", ".join(resource.depends_on)
        lines.append(f"  depends_on = [{refs}]")

    lines.append("}")
    return "\n".join(lines)


def _render_module(
    resource: Resource,
    override: "ModuleOverride",
    conventions: "ConventionProfile",
) -> str:
    """Render a Terraform module block using the org's module override.

    Properties are translated through override.input_map, with override.passthrough
    names emitted as-is. Any remaining properties are dropped with a warning.
    """
    module_name = override.resolve_name(
        resource.component,
        resource.type,
        conventions.naming.type_short_map,
    )
    lines = [f'module "{module_name}" {{']
    lines.append(f'  source = "{override.source}"')
    lines.append('')

    props = {k: v for k, v in resource.properties.items() if k != "tags"}
    emitted: set[str] = set()
    dropped: list[str] = []

    # Mapped inputs
    for prop_name, module_var in override.input_map.items():
        if prop_name in props:
            rendered = _hcl_value(props[prop_name], indent=1)
            lines.append(f"  {module_var} = {rendered}")
            emitted.add(prop_name)

    # Passthrough inputs
    for prop_name in override.passthrough:
        if prop_name in props:
            rendered = _hcl_value(props[prop_name], indent=1)
            lines.append(f"  {prop_name} = {rendered}")
            emitted.add(prop_name)

    # Collect dropped properties and warn
    for prop_name in props:
        if prop_name not in emitted:
            dropped.append(prop_name)

    if dropped:
        warnings.warn(
            f"module '{module_name}' ({override.match}): "
            f"{len(dropped)} unmapped propert{'y' if len(dropped) == 1 else 'ies'} dropped: "
            f"{', '.join(dropped)}. Add to input_map or passthrough in conventions.yaml.",
            stacklevel=2,
        )

    # Tags block (pass through as-is if present)
    merged_tags = {**resource.properties.get("tags", {}), **resource.tags}
    if merged_tags:
        lines.append('')
        lines.append("  tags = {")
        for k, v in sorted(merged_tags.items()):
            lines.append(f'    {k} = "{v}"')
        lines.append("  }")

    lines.append("}")
    return "\n".join(lines)


def _render_data_source(resource: Resource) -> str:
    """Render a Terraform data source block: data "type" "name" { ... }

    Data sources look up existing resources. They have no tags and no
    depends_on — they are read-only references to pre-existing infra.
    """
    lines = [f'data "{resource.type}" "{resource.logical_name}" {{']
    for key, value in resource.properties.items():
        rendered = _hcl_value(value, indent=1)
        lines.append(f"  {key} = {rendered}")
    lines.append("}")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HCL value serialisation
# ---------------------------------------------------------------------------


def _hcl_value(value: Any, indent: int = 0) -> str:
    """Recursively serialise a Python value to its HCL representation.

    Special case: string values wrapped in ``${...}`` are treated as Terraform
    expression references and rendered without quotes.
    """
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        if _is_tf_reference(value):
            return value[2:-1]  # strip ${ and }
        return f'"{_escape_hcl_string(value)}"'
    if isinstance(value, list):
        return _hcl_list(value, indent)
    if isinstance(value, dict):
        return _hcl_map(value, indent)
    # Fallback for anything unexpected
    return f'"{value}"'


def _is_tf_reference(value: str) -> bool:
    """True if the string is a Terraform expression reference: ${...}"""
    return value.startswith("${") and value.endswith("}")


def _escape_hcl_string(value: str) -> str:
    """Escape characters that need escaping inside HCL double-quoted strings."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\r", "\\r")


def _hcl_list(items: list, indent: int) -> str:
    if not items:
        return "[]"
    pad = "  " * (indent + 1)
    close = "  " * indent
    rendered = [_hcl_value(item, indent + 1) for item in items]

    # Single-line if all items are scalars and the line would be short
    if all(_is_scalar(item) for item in items):
        oneliner = "[" + ", ".join(rendered) + "]"
        if len(oneliner) <= 80:
            return oneliner

    inner = "\n".join(f"{pad}{r}," for r in rendered)
    return f"[\n{inner}\n{close}]"


def _hcl_map(mapping: dict, indent: int) -> str:
    if not mapping:
        return "{}"
    pad = "  " * (indent + 1)
    close = "  " * indent
    lines = []
    for k, v in mapping.items():
        lines.append(f"{pad}{k} = {_hcl_value(v, indent + 1)}")
    return "{\n" + "\n".join(lines) + f"\n{close}}}"


def _is_scalar(value: Any) -> bool:
    return isinstance(value, (bool, int, float, str)) or value is None
